CREATE TABLE UI_BOARD(
    SEQ NUMBER(5) PRIMARY KEY,--게시글 번호
    TITLE VARCHAR2(200), -- 게시글 제목
    WRITER VARCHAR2(20), -- 작성자
    CONTENT VARCHAR2(2000), -- 게시글 내용
    REGDATE DATE DEFAULT SYSDATE,-- 작성날짜
    CNT NUMBER(5) DEFAULT 0, --기본값
    CATEGORY_ID NUMBER,
    FOREIGN KEY (CATEGORY_ID) REFERENCES UI_CATEGORY(ID)
);
CREATE SEQUENCE UI_BOARD_SEQ 
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOCYCLE
    NOCACHE;
    
CREATE TABLE UI_CATEGORY (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50)
);
    
SELECT * FROM UI_BOARD ORDER BY seq DESC;

